Repository Codehagen/Badget, pull requests merged in 2024-02, with the labels that each got.

#123 Fix/101 replace ci build step with typecheck
  .env.example
  .github/workflows/ci.yml
  .github/workflows/on-push.yml
  apps/www/package.json
  package.json
  packages/api/package.json
  packages/db/src/index.ts
  packages/stripe/package.json
  pnpm-lock.yaml
  tooling/github/package.json
  tooling/github/setup/action.yml
Labels: 🔄 CI/CD

#135 fix: remove last Plaid leftovers
  packages/db/src/enum.ts
  packages/db/src/index.ts
  packages/db/src/schema/account.ts
  packages/db/src/schema/institution.ts
  packages/db/src/schema/resource.ts
  packages/db/src/schema/transaction.ts
Labels: 🧙 backend

#158 fix: multiple calls
  apps/www/app/api/trpc/edge/[trpc]/route.ts
  apps/www/app/api/trpc/lambda/[trpc]/route.ts
  apps/www/components/layout/user-account-nav.tsx
  apps/www/next.config.js
  apps/www/package.json
  apps/www/trpc/client.ts
  apps/www/trpc/server.ts
  packages/api/package.json
  packages/api/src/router/stripe.ts
  packages/api/src/trpc.ts
  packages/db/package.json
  packages/stripe/src/webhooks.ts
  pnpm-lock.yaml
Labels: 🐛 bug
